### ISSUE TITLE
Real-time inference?

### ISSUE THREAD

**Issue by FedericoVasile1** [gengshan-y/VCN#19]
Hi, I congrats for your work.
I would like to know whether at inference time is it possible to use this model as part of a framework that performs the online action detection task? (i.e. let's suppose I have an input stream video, is the model able to compute optical-flow features as the frames arrive, with real-time speed ?)

Thank you!

**Comment by gengshan-y** [comment]
Hi, the running time depends on a lot of other factors, including the hardware and the image size. The running time of VCN on KITTI sized image (1248x384) is 0.18s/pair on TITAN XP GPU. However, if you can afford to down-sample the video, VCN can be made "real-time".

In general, the benefit of VCN architecture is not fully revealed on popular GPU devices, possibly due to the high cost of memory access. If you are looking for a practically faster optical flow network, you could try PWC-Net , RAFT or [Nvidia's optical flow SDK](https://developer.nvidia.com/opticalflow-sdk).

**Comment by FedericoVasile1** [comment]
Awesome! Thank you so much!
