### ISSUE TITLE
why training iteration is 220K

### ISSUE THREAD

**Issue by pz0910** [gengshan-y/VCN#3]
Hi, thanks for your great work.
I am confused that training iteration mentioned in your paper is 220k instead of 150k(80k for flying chairs and 70k for flying things).
Can you help me out here?

**Comment by gengshan-y** [comment]
Please see the updated version of the paper: 
http://www.contrib.andrew.cmu.edu/~gengshay/wordpress/wp-content/uploads/2019/11/vcn.pdf

We train on chairs/things with more iterations in the final version, but it turns out not all numbers in the paper have been updated accordingly. Thanks for pointing it out.

**Comment by pz0910** [comment]
> Please see the updated version of the paper:
> http://www.contrib.andrew.cmu.edu/~gengshay/wordpress/wp-content/uploads/2019/11/vcn.pdf
> 
> We train on chairs/things with more iterations in the final version, but it turns out not all numbers in the paper have been updated accordingly. Thanks for pointing it out.

thanks for replying
