### ISSUE TITLE
How to evaluate on KITTI and Sintel

### ISSUE THREAD

**Issue by ghost** [gengshan-y/VCN#5]
Hi gengshan~~ Thanks for your wonderful work and code!

I have done the three training stage: FlyingChairs->FlyingThings->KITTI. I tried the following code to evaluate my model:
```
modelname=kitti-ft-trainval
i=149999
CUDA_VISIBLE_DEVICES=0 python submission.py --dataset 2015 --datapath /ssd/kitti_scene/training/   --outdir ./weights/$modelname/ --loadmodel ./weights/$modelname/finetune_$i.tar  --maxdisp 512 --fac 2
python eval_tmp.py --path ./weights/$modelname/ --vis no --dataset 2015
```

But I get the following error:
```
epe = np.sqrt(np.power(gtflow - flow,2).sum(-1))[mask]
ValueError: operands could not be broadcast together with shapes (370,1224,2) (375,1242,2)
```

Another problem is how to finetune my model on Sintel, I am confused with the "rob_devkit" tool. When I run `python flow_devkit.py`, it asks me which format to use. There are two choices: middlebury and kitti. Which format should I use? I tried to use kitti format, and get the following folder structure:
```
rob_devkit/
    flow/
        datasets_kitti2015/
            metadata/
            test/
            training/
            bundler/
```
But in your `main.py`, the sintel dataset is loaded by `iml0, iml1, flowl0 = ls.dataloader('%s/rob_flow/training/'%args.database)`. I don't know where to find the `rob_flow`.

I am a newcomer to this field and puzzled by these problems for several days. Could you please help me?

**Comment by gengshan-y** [comment]
> `ValueError: operands could not be broadcast together with shapes (370,1224,2) (375,1242,2)`

I don't see this error. This is due to the shape mismatch between flow ground-truth and your prediction. Can you make sure the shape of the input image is identical to the shape of the ground-truth? Note KITTI has both 370x1224 and 375x1242 images.

> But in your main.py, the sintel dataset is loaded by iml0, iml1, flowl0 = ls.dataloader('%s/rob_flow/training/'%args.database). I don't know where to find the rob_flow.

You could move/link folder `datasets_kitti2015` as a subfolder `rob_flow` in your dataset folder and try again. There should be 3373 images in rob_flow/training/flow_occ. 

Let me know if you have further questions.

**Comment by ghost** [comment]
Thanks for your immediate reply!

I found the error is caused by `000155_10.png`. In `submission.py`, the shape of this image is 1242. But in `eval_tmp.py`, the shape of ground-truth is 1224. I am confused by this bug.

I also tried `--dataset 2015test`. However, there is no pathway named `kitti_scene/testing/flow_occ` in my computer, which seems necessary for `eval_tmp.py`. My kitti dataset is unzipped from `data_scene_flow.zip` directly, and I do not find `kitti_scene/testing/flow_occ`.

Besides, I am not sure whether my training process is correct. I want to confirm the following details:

1. Before I finetune the FlyingChair model on FlyingThings dataset, must I resume the number of iterations?  I find that the learning rate still starts with 1e-3 on FlyingThings if I do not resume the number of iterations. But when I finetune on KITTI, it seems that I do not need to resume the number of iterations.
2. Before I finetune on KITTI, should I run `dataloader/kitti15list_val.py`, `dataloader/kitti15list_train.py` ?
3. If I want to reproduce the KITTI result in your paper, which stage (`2015train` or `2015trainval`) should I use to train? which stage (`2015` or `2015test`) should I use to test? 
4. To run + visualize on KITTI-15 test set, you use `CUDA_VISIBLE_DEVICES=0 python submission.py --dataset 2015test --datapath dataset/kitti_scene/testing/   --outdir ./weights/$modelname/ --loadmodel ./weights/$modelname/finetune_$i.tar  --maxdisp 512 --fac 2`. When evaluating on KITTI-val, you use `CUDA_VISIBLE_DEVICES=0 python submission.py --dataset 2015 --datapath /ssd/kitti_scene/training/   --outdir ./weights/$modelname/ --loadmodel ./weights/$modelname/finetune_$i.tar  --maxdisp 512 --fac 2`. The `dataset/kitti_scene/testing/` seems to be a relative directory; but `/ssd/kitti_scene/training/` seems to be an absolute directory. So where should I put my KITTI dataset?
5. As is mentioned above, several bugs occur when I test on KITTI. It may caused by mismatched folder structure. My KITTI dataset is unzipped from `data_scene_flow.zip` directly. I want to know the details for preparing KITTI dataset for runing your code. 

Could you please help me?

**Comment by gengshan-y** [comment]
> I found the error is caused by 000155_10.png. In submission.py, the shape of this image is 1242. But in eval_tmp.py, the shape of ground-truth is 1224. I am confused by this bug.

This is not a bug of the code. Can you check again with the official KITTI 2015 scene flow dataset? The size of `data_scene_flow/training/image_2/000155_10.png` should be 1224x370x3.

> I also tried --dataset 2015test.

I'm assuming you want to visualize the flow, since ground-truth for test data is held-out. Did you pass --vis? You can refer to **Evaluate on KITTI-15 benchmark** section.

To reproduce numbers in the paper, just follow the pre-training and fine-tuning procedure listed as cmmand in readme. So for you questions

1. Yes
2. That's just for your own records. i.e., to get training error and validation error.
3. train with 2015trainval, test with 2015test
4. put KITTI anywhere you like and change the path accordingly
5. rename data_scene_flow as kitti_scene

Free free to reopen if you have further questions.

**Comment by ghost** [comment]
Thanks for your help!
